server:
  port: 8089
  tomcat:
    basedir: D:/tomcat/temp

spring:
  security:
    user:
      name: baidu
      password: zhang963.
  application:
    name: config-server
  profiles:
    # 使用本地配置文件
    active: native

  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://github.com/zhangfeiyanggg/zhangfeiyang.git
          # 配置文件所在目录
          search-paths: config
          # git账号
          username: zhangfeiyanggg
          # git密码
          password: z3301337651

        default-label: master